In [1]:
# Why is this not just a standard feature of every notebook?
%load_ext autoreload
%autoreload 2

In [2]:
from kpl_layers import polynomial
import torch

In [3]:
x1 = polynomial.MonomialLayer(1,2)

In [4]:
x1.m_ind

tensor([[1, 0],
        [1, 1]], dtype=torch.int32)

In [5]:
x1.n_inputs

1

In [6]:
x1.n_outputs

2

In [7]:
out1 = x1.forward(torch.Tensor([[0.],[1.],[2.],[3.]]))
print(out1)

tensor([[0., 0.],
        [1., 1.],
        [2., 4.],
        [3., 9.]])


In [8]:
x2 = polynomial.MonomialLayer(16,2)

In [9]:
x2.m_ind

tensor([[ 1,  0],
        [ 1,  1],
        [ 2,  0],
        [ 2,  1],
        [ 2,  2],
        [ 3,  0],
        [ 3,  1],
        [ 3,  2],
        [ 3,  3],
        [ 4,  0],
        [ 4,  1],
        [ 4,  2],
        [ 4,  3],
        [ 4,  4],
        [ 5,  0],
        [ 5,  1],
        [ 5,  2],
        [ 5,  3],
        [ 5,  4],
        [ 5,  5],
        [ 6,  0],
        [ 6,  1],
        [ 6,  2],
        [ 6,  3],
        [ 6,  4],
        [ 6,  5],
        [ 6,  6],
        [ 7,  0],
        [ 7,  1],
        [ 7,  2],
        [ 7,  3],
        [ 7,  4],
        [ 7,  5],
        [ 7,  6],
        [ 7,  7],
        [ 8,  0],
        [ 8,  1],
        [ 8,  2],
        [ 8,  3],
        [ 8,  4],
        [ 8,  5],
        [ 8,  6],
        [ 8,  7],
        [ 8,  8],
        [ 9,  0],
        [ 9,  1],
        [ 9,  2],
        [ 9,  3],
        [ 9,  4],
        [ 9,  5],
        [ 9,  6],
        [ 9,  7],
        [ 9,  8],
        [ 9,  9],
        [10,  0],
        [1

In [10]:
x2.n_outputs

152

In [11]:
input2 = torch.zeros(20,16)
input2[0:16,:] = torch.eye(16)
input2[16,[0,1]]=2
input2[17,[0,9]]=3
input2[18,[1,7]]=4
input2[19,[14,15]]=5
out2 = x2.forward(input2)
print(out2)
print(out2.shape)

tensor([[ 1.,  1.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        ...,
        [ 3.,  9.,  0.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  4.,  ...,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  ...,  0., 25., 25.]])
torch.Size([20, 152])


In [12]:
x3 = polynomial.MonomialLayer(2,3)

In [13]:
x3.m_ind

tensor([[1, 0, 0],
        [1, 1, 0],
        [1, 1, 1],
        [2, 0, 0],
        [2, 1, 0],
        [2, 1, 1],
        [2, 2, 0],
        [2, 2, 1],
        [2, 2, 2]], dtype=torch.int32)

In [14]:
x3.n_outputs

9

In [15]:
out3 = x3.forward(torch.Tensor([[1.1,0.9],[1.,2.],[0.,1.],[3.,4.]]))
print(out3)
print(out3.shape)

tensor([[ 1.1000,  1.2100,  1.3310,  0.9000,  0.9900,  1.0890,  0.8100,  0.8910,
          0.7290],
        [ 1.0000,  1.0000,  1.0000,  2.0000,  2.0000,  2.0000,  4.0000,  4.0000,
          8.0000],
        [ 0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  1.0000,  0.0000,
          1.0000],
        [ 3.0000,  9.0000, 27.0000,  4.0000, 12.0000, 36.0000, 16.0000, 48.0000,
         64.0000]])
torch.Size([4, 9])


In [16]:
x4 = polynomial.MonomialLayer(2,7)

In [17]:
x4.m_ind

tensor([[1, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1],
        [2, 0, 0, 0, 0, 0, 0],
        [2, 1, 0, 0, 0, 0, 0],
        [2, 1, 1, 0, 0, 0, 0],
        [2, 1, 1, 1, 0, 0, 0],
        [2, 1, 1, 1, 1, 0, 0],
        [2, 1, 1, 1, 1, 1, 0],
        [2, 1, 1, 1, 1, 1, 1],
        [2, 2, 0, 0, 0, 0, 0],
        [2, 2, 1, 0, 0, 0, 0],
        [2, 2, 1, 1, 0, 0, 0],
        [2, 2, 1, 1, 1, 0, 0],
        [2, 2, 1, 1, 1, 1, 0],
        [2, 2, 1, 1, 1, 1, 1],
        [2, 2, 2, 0, 0, 0, 0],
        [2, 2, 2, 1, 0, 0, 0],
        [2, 2, 2, 1, 1, 0, 0],
        [2, 2, 2, 1, 1, 1, 0],
        [2, 2, 2, 1, 1, 1, 1],
        [2, 2, 2, 2, 0, 0, 0],
        [2, 2, 2, 2, 1, 0, 0],
        [2, 2, 2, 2, 1, 1, 0],
        [2, 2, 2, 2, 1, 1, 1],
        [2, 2, 2, 2, 2, 0, 0],
        [2, 2, 2, 2, 2, 1, 0],
        [2, 2, 2, 2, 2, 1, 1],
        

In [18]:
x4.n_outputs

35

In [19]:
out4 = x4.forward(torch.Tensor([[1.1,0.9],[1.,2.],[0.,1.],[3.,4.]]))
print(out4)
print(out4.shape)

tensor([[1.1000e+00, 1.2100e+00, 1.3310e+00, 1.4641e+00, 1.6105e+00, 1.7716e+00,
         1.9487e+00, 9.0000e-01, 9.9000e-01, 1.0890e+00, 1.1979e+00, 1.3177e+00,
         1.4495e+00, 1.5944e+00, 8.1000e-01, 8.9100e-01, 9.8010e-01, 1.0781e+00,
         1.1859e+00, 1.3045e+00, 7.2900e-01, 8.0190e-01, 8.8209e-01, 9.7030e-01,
         1.0673e+00, 6.5610e-01, 7.2171e-01, 7.9388e-01, 8.7327e-01, 5.9049e-01,
         6.4954e-01, 7.1449e-01, 5.3144e-01, 5.8459e-01, 4.7830e-01],
        [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
         1.0000e+00, 2.0000e+00, 2.0000e+00, 2.0000e+00, 2.0000e+00, 2.0000e+00,
         2.0000e+00, 2.0000e+00, 4.0000e+00, 4.0000e+00, 4.0000e+00, 4.0000e+00,
         4.0000e+00, 4.0000e+00, 8.0000e+00, 8.0000e+00, 8.0000e+00, 8.0000e+00,
         8.0000e+00, 1.6000e+01, 1.6000e+01, 1.6000e+01, 1.6000e+01, 3.2000e+01,
         3.2000e+01, 3.2000e+01, 6.4000e+01, 6.4000e+01, 1.2800e+02],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.000